config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  get 'dashboard', to: 'dashboard#index', as: :dashboard
  get '/home', to: 'home#index', as: 'home'
  get '/login', to: 'home#login', as: 'login'
  get "goals/my_transaction", to: "goals#my_transaction"
  post "create_goal_transaction", to: "goals#create_goal_transaction"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  resources :my_transactions, only: [:destroy, :update, :edit, :index, :show]
  get 'all_transactions', to: 'my_transactions#all_transactions'

  resources :accounts do
    resources :my_transactions, only: [:edit, :update, :index, :new, :create, :destroy]
  end

  resources :balances, only: [:edit, :update, :show]
  resources :goals
  resources :questions, only: [:index, :create]

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user! , only: [:index, :login]

  def home
  end

  def index
    @user = current_user
    @accounts = current_user.accounts
    @goals = current_user.goals
  end

  def login
    @user = current_user
    @accounts = current_user.accounts
    #@goals = current_user.goals
  end
end

app/views/home/index.html.erb
<div class="container mt-5">
  <div class="text-center mb-4">
    <h1 class="display-4 text-success">Tu Dashboard Financiero</h1>
    <p class="lead text-secondary">Lleva el control de tus finanzas de manera efectiva.</p>
    <hr class="w-50 mx-auto" style="border-top: 3px solid #28a745;">
  </div>

  <div class="d-flex flex-column flex-lg-row gap-3">
    <div class="d-flex flex-column gap-3 w-100">
      <div class="d-flex flex-row justify-content-between gap-4">
        <div class="mb-4 custom-card card-rectangle hover-effect" style="background-image: url('/path/to/accounts.jpg'); flex: 1; margin-right: 10px;"> <!-- Agregar margin-right -->
          <div class="card-body text-center d-flex flex-column justify-content-center align-items-center" style="height: 200px;">
            <i class="fas fa-wallet text-success mb-3" style="font-size: 2rem;"></i>
            <h5 class="card-title text-dark font-weight-bold">Cuentas Registradas</h5>
            <h3 class="text-success"><%= @user.accounts.count %> </h3>
            <a href="<%= accounts_path %>" class="btn btn-success btn-sm mx-1">Gestionar Cuentas</a>
          </div>
        </div>

        <div class="mb-4 custom-card card-rectangle hover-effect" style="background-image: url('/path/to/accounts.jpg'); flex: 1;">
          <div class="card-body text-center d-flex flex-column justify-content-center align-items-center" style="height: 200px;">
            <i class="fas fa-question-circle text-success mb-3" style="font-size: 2rem;"></i>
            <h5 class="card-title text-dark font-weight-bold">Consulta al asistente</h5>
            <div class="mt-3"> <!-- Espacio adicional entre el título y el botón -->
              <a href="<%= questions_path %>" class="btn btn-success btn-sm mx-1">Asistente</a>
            </div>
          </div>
        </div>
      </div>

      <div class="d-flex flex-row justify-content-between gap-4">
        <div class="mb-4 custom-card card-rectangle hover-effect" style="background-image: url('/path/to/goals.jpg'); flex: 1; margin-right: 10px;"> <!-- Agregar margin-right -->
          <div class="card-body text-center d-flex flex-column justify-content-center align-items-center" style="height: 200px;">
            <i class="fas fa-bullseye text-success mb-3" style="font-size: 2rem;"></i>
            <h5 class="card-title text-dark font-weight-bold">Objetivos Activos</h5>
            <h3 class="text-success"><%= @user.goals.count %> </h3>
            <a href="<%= goals_path %>" class="btn btn-success btn-sm mx-1">Gestionar Objetivos</a>
          </div>
        </div>

        <div class="mb-4 custom-card card-rectangle hover-effect" style="background-image: url('/path/to/accounts.jpg'); flex: 1;">
          <div class="card-body text-center d-flex flex-column justify-content-center align-items-center" style="height: 200px;">
            <i class="fas fa-exchange-alt text-success mb-3" style="font-size: 2rem;"></i>
            <h5 class="card-title text-dark font-weight-bold">Transacciones</h5>
            <h3 class="text-success"><%= @user.my_transactions.count %> </h3>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="mt-5 py-4 bg-light text-center" style="width: calc(100% - 30px); margin-left: auto; margin-right: auto;">
    <h6 class="text-secondary">¡Es hora de registrar tu último gasto!</h6>
    <p class="mb-4 text-muted">Utiliza nuestras herramientas para organizar tu presupuesto.</p>
  </div>
</div>





 <i class="fas fa-question-circle text-success mb-3" style="font-size: 2rem;"></i>

app/views/home/login.html.erb
<div class="container mt-5">
  <div class="text-center mb-4">
    <h1 class="display-4 text-success">¡Bienvenido, <%= @user.name || @user.email %> </h1>
    <p class="lead text-secondary">Explora tu panel y administra tus objetivos y cuentas</p>
    <hr class="w-50 mx-auto" style="border-top: 3px solid #28a745;">
  </div>

  <div class="text-center mb-6">
    <div class="mb-4 custom-card card-rectangle hover-effect" style="background-image: url('/path/to/goals.jpg');">
      <div class="card-body text-center d-flex flex-column justify-content-center align-items-center" style="height: 200px;">
        <i class="fa-regular fa-map text-success mb-3" style="font-size: 2rem;"></i>
        <h5 class="card-title text-dark font-weight-bold">Dashboard</h5>
        <a href="<%= home_path %>" class="btn btn-success btn-sm mx-1">Ir al Dashboard</a>
      </div>
    </div>
  </div>
  <div class="mb-4 custom-card card-rectangle hover-effect" style="background-image: url('/path/to/accounts.jpg');">
    <div class="card-body text-center d-flex flex-column justify-content-center align-items-center" style="height: 200px;">
      <i class="fas fa-wallet text-success mb-3" style="font-size: 2rem;"></i>
      <h5 class="card-title text-dark font-weight-bold">Tus Cuentas</h5>
      <a href="<%= accounts_path %>" class="btn btn-success btn-sm mx-1">Gestionar Cuentas</a>
    </div>
  </div>
  <div class="mb-4 custom-card card-rectangle hover-effect" style="background-image: url('/path/to/goals.jpg');">
    <div class="card-body text-center d-flex flex-column justify-content-center align-items-center" style="height: 200px;">
      <i class="fas fa-bullseye text-success mb-3" style="font-size: 2rem;"></i>
      <h5 class="card-title text-dark font-weight-bold">Tus Objetivos</h5>
      <a href="<%= goals_path %>" class="btn btn-success btn-sm mx-1">Gestionar Objetivos</a>
    </div>
  </div>
  <div class="mt-5 py-4 bg-light text-center">
    <h6 class="text-secondary">¡Es hora de registrar tu último gasto!</h6>
    <p class="mb-4 text-muted">Utiliza nuestras herramientas para organizar tu presupuesto.</p>
  </div>
</div>