config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  get 'dashboard', to: 'dashboard#index', as: :dashboard
  get '/home', to: 'home#index', as: 'home'
  get '/login', to: 'home#login', as: 'login'
  get "goals/my_transaction", to: "goals#my_transaction"
  post "create_goal_transaction", to: "goals#create_goal_transaction"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  resources :my_transactions, only: [:destroy, :update, :edit, :index, :show]
  get 'all_transactions', to: 'my_transactions#all_transactions'

  resources :accounts do
    resources :my_transactions, only: [:edit, :update, :index, :new, :create, :destroy]
  end

  resources :balances, only: [:edit, :update, :show]
  resources :goals
  resources :questions, only: [:index, :create]

end

app/models/balance.rb
class Balance < ApplicationRecord
  belongs_to :account
  before_save :status_check
  
  def status_check
    if total_amount.positive?
      self.status = true
    else
      self.status = false
    end
  end
end

app/controllers/balances_controller.rb
class BalancesController < ApplicationController
  before_action :set_account, only: [:show]
  before_action :set_balance, only: [:show, :edit, :update, :destroy]
  def index
    @balances = Balance.all
  end

  def show
  end

  def new
    @balance = Balance.new
  end

  def create
    @balance = Balance.new(balance_params)
    if @balance.save
      redirect_to balance_path(@balance)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @balance.update(balance_params)
      redirect_to balance_path(@balance)
    else
      render :edit
    end
  end

  def destroy
    @balance.destroy
    redirect_to balances_path, status: :see_other
  end

  private

  def balance_params
    params.require(:balance).permit(:account_id, :total_amount, :status)
  end

  def set_account
    @account = Account.find_by(id: params[:account_id])
    redirect_to accounts_path, alert: "Cuenta no encontrada" unless @account
  end

  def set_balance
    return unless @account
    @balance = @account.balance
    redirect_to account_path(@account), alert: "el balance no existe" unless @balance
  end
end

app/views/balances/_form.html.erb
<%= form_with model: balance do |f| %>
  <%= f.label :account_id %>
  <%= f.number_field :account_id %>

  <%= f.label :total_amount %>
  <%= f.text_field :total_amount %>

  <%= f.label :status %>
  <%= f.text_field :status %>

  <%= f.submit %>
<% end %>

app/views/balances/edit.html.erb
<%= render "form", balance: @balance %>

app/views/balances/index.html.erb
<ul>
  <% @balances.each do |balance| %>
    <li><%= link_to balance.account_id,
    balance_path(balance) %></li>
  <% end %>
</ul>

app/views/balances/new.html.erb
<%= render "form", balance: @balance %>

app/views/balances/show.html.erb
<h2><%= @balance.account_id %></h2>
<p><%= @balance.total_amount %></p>
<p><%= @balance.status %></p>
<%= link_to "Delete",
  account_balance_path(@account, @balance), class: "btn btn-danger btn-sm",
  data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
%>
<%= link_to "Edit",  edit_account_balance_path(@balance), class: "btn btn-warning btn-sm" %>