config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  get 'dashboard', to: 'dashboard#index', as: :dashboard
  get '/home', to: 'home#index', as: 'home'
  get '/login', to: 'home#login', as: 'login'
  get "goals/my_transaction", to: "goals#my_transaction"
  post "create_goal_transaction", to: "goals#create_goal_transaction"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  resources :my_transactions, only: [:destroy, :update, :edit, :index, :show]
  get 'all_transactions', to: 'my_transactions#all_transactions'

  resources :accounts do
    resources :my_transactions, only: [:edit, :update, :index, :new, :create, :destroy]
  end

  resources :balances, only: [:edit, :update, :show]
  resources :goals
  resources :questions, only: [:index, :create]

end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :user
  has_one :balance
  has_one :balance, dependent: :destroy
  has_many :my_transactions
  validates :bank, :account_type, :currency, presence: true
  after_create :create_balance

  def create_balance
    Balance.create!(account: self, total_amount: 0, status: true)
  end

end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: [:show, :edit, :update, :destroy]
  def index
    @accounts = Account.all
  end

  def show
    @transactions = @account.my_transactions
  end

  def new
    @account = Account.new
  end

  # def create
  #   @account = Account.new(account_params)
  #   @account.user = current_user
  #   if @account.save
  #     # @account.balance = Balance.create(total_amount: 0, status: true)
  #     @account.balance = Balance.create(account: @account, total_amount: 0, status: true)
  #     redirect_to account_path(@account)
  #   else
  #     render :new
  #   end
  # end
  def create
    @account = Account.new(account_params)
    @account.user = current_user
    if @account.save
      redirect_to account_path(@account)
    else
      render :new, status: :unprocessable_entity, alert: "We had a problem processing your goal"
    end
  end

  def edit
  end

  def update
    if @account.update(account_params)
      redirect_to account_path(@account)
    else
      render :edit, status: :unprocessable_entity, alert: "We had a problem processing your goal"
    end
  end

  def destroy
    @account.destroy
    redirect_to accounts_path, status: :see_other
  end

  private

  def account_params
    params.require(:account).permit(:bank, :account_type, :user_id, :currency)
  end

  def set_account
    @account = Account.find(params[:id])
    # if @account.nil?
    #   redirect_to account_path, alert: "acount no encontrado"
    # end
  end
end

app/views/accounts/_form.html.erb
<div class="container w-25 border rounded shadow-lg mt-5 p-4 bg-light">
  <h2 class="text-center mb-4">
    <strong><%= account.persisted? ? "Edita tu cuenta! ✏️" : "Crea tu cuenta! 📜" %></strong> 🧑🏼‍💻
  </h2>

  <%= simple_form_for(account, html: { class: "needs-validation", novalidate: true }) do |f| %>
    <div class="mb-3">
     <%= f.input :bank,
            label: "Banco:",
            label_html: { class: "form-label fw-bold" },
            input_html: {
              class: "form-control",
              data: {
                controller: "capitalize",
                capitalize_target: "bank",
                action: "keyup->capitalize#capitalize"
              }
            },
            required: false %>
    </div>

    <div class="mb-3">
      <%= f.input :account_type,
                  label: "Tipo de cuenta:",
                  label_html: { class: "form-label fw-bold" },
                  as: :select,
                  collection: ["Credito", "Debito"],
                  include_blank: "Selecciona tipo de cuenta",
                  input_html: { class: "form-select" },
                  required: false %>
    </div>

    <div class="mb-3">
      <%= f.input :currency,
                  label: "Divisa:",
                  label_html: { class: "form-label fw-bold" },
                  as: :select,
                  collection: [
                    "USD - Dólar estadounidense", "EUR - Euro", "JPY - Yen japonés",
                    "MXN - Peso mexicano", "PEN - Sol peruano", "CLP - Peso chileno",
                    "ARS - Peso argentino", "BRL - Real brasileño", "BOB - Boliviano",
                    "GBP - Libra esterlina", "CHF - Franco suizo", "CAD - Dólar canadiense",
                    "AUD - Dólar australiano", "CNY - Renminbi o Yuan", "INR - Rupia india",
                    "RUB - Rublo ruso", "KRW - Won surcoreano", "SGD - Dólar de Singapur",
                    "MYR - Ringgit malasio", "SEK - Corona sueca", "NOK - Corona noruega",
                    "COP - Peso colombiano", "DKK - Corona danesa", "ESP - Peseta española",
                    "TRY - Lira turca", "AED - Dirham de los Emiratos Árabes Unidos",
                    "ZAR - Rand sudafricano", "THB - Baht tailandés", "HUF - Florín húngaro",
                    "ISK - Corona islandesa", "TWD - Nuevo dólar taiwanés", "PHP - Peso filipino",
                    "AWG - Florín arubeño", "NZD - Dólar neozelandés", "PKR - Rupia pakistaní",
                    "KZT - Tenge kazajo", "HKD - Dólar de Hong Kong", "DZD - Dinar argelino",
                    "EGP - Libra egipcia", "VND - Dong vietnamita"
                  ],
                  include_blank: "Selecciona una moneda",
                  input_html: { class: "form-select" },
                  required: false %>
    </div>

    <div class="mb-3">
      <%= f.submit account.persisted? ? "Actualizar cuenta" : "Crear cuenta", class: "btn btn-success w-100" %>
    </div>

    <div class="text-center mt-3">
           <%= link_to "Cancelar",
            account.persisted? ? account_path(account) : accounts_path,
            class: "text-muted small text-decoration-none",
            data: { bs_toggle: "tooltip" },
            title: account.persisted? ? "Volver al detalle de la cuenta" : "Volver a la lista de cuentas" %>
    </div>
  <% end %>
</div>

app/views/accounts/edit.html.erb
<%= render "form", account: @account %>

app/views/accounts/index.html.erb
<div class="container my-5 position-relative">

  <div class="text-center mb-4">
    <h1 class="display-4 text-success">¡Tus Cuentas! <i class="fa-solid fa-money-check-dollar"></i></h1>
    <p class="lead text-secondary">Administra tus cuentas de forma sencilla y rápida.</p>
    <hr class="w-50 mx-auto" style="border-top: 3px solid #28a745;">
  </div>

<div class="row justify-content-center">
  <% @accounts.each do |account| %>
    <div
      class="col-md-4 col-sm-6 mb-4"
      data-controller="currency-symbol"
      data-currency="<%= account.currency %>"
    >
      <div class="card shadow-lg h-100 border-0">
        <div class="card-body text-center">
          <i class="fa-solid fa-file-invoice-dollar text-info mb-3" style="font-size: 2rem;"></i>
          <h5 class="card-title text-dark font-weight-bold"><%= account.bank %></h5>
          <h6 class="card-subtitle text-muted mb-3">
            <%= account.account_type.capitalize %>
          </h6>
          <p class="text-success fs-5 fw-bold mb-4">
            <span data-controller="currency-symbol" data-currency="<%= account.currency %>">
              <%= number_to_currency(account.balance.total_amount, unit: "", delimiter: ",") %>
            </span>
          </p>
          <%= link_to "Detalles", account_path(account), class: "btn btn-success btn-sm mx-1" %>
          <%= link_to "Editar", edit_account_path(account), class: "btn btn-outline-dark btn-sm mx-1" %>
        </div>
      </div>
    </div>
  <% end %>
</div>

  <div class="d-flex justify-content-between align-items-center mt-5">
    <%= link_to "← Atrás", login_path, class: "btn btn-outline-success btn-sm" %>
    <%= link_to "Agregar una cuenta", new_account_path, class: "btn btn-success btn-sm" %>
  </div>


  <div class="mt-5 py-4 bg-light text-center">
    <h6 class="text-secondary">¿Necesitas ayuda para gestionar tus cuentas?</h6>
    <p class="mb-4 text-muted">Consulta nuestras guías y recursos para administrar tus finanzas.</p>
  </div>
</div>

app/views/accounts/new.html.erb
<%= render "form", account: @account %>

app/views/accounts/show.html.erb
<div class="container mt-4">
  <div class="card shadow-lg rounded-4 border-0">
    <div class="card-body p-4">
      <div class="d-flex justify-content-between align-items-center mb-4">
        <h2 class="card-title text-success m-0">
          <i class="fa-solid fa-file-invoice-dollar me-2"></i>Detalles de Cuenta
        </h2>
        <span class="badge bg-success rounded-pill">
          <%= @account.bank %>
        </span>
      </div>

      <div class="row g-3" >
        <div class="col-md-6">
          <div class="bg-light p-3 rounded-3">
            <small class="text-muted d-block mb-1">Tipo de Cuenta</small>
            <p class="fw-bold mb-0"><%= @account.account_type %></p>
          </div>
        </div>
        <div class="col-md-6">
          <div class="bg-light p-3 rounded-3">
            <small class="text-muted d-block mb-1">Código de Usuario</small>
            <p class="fw-bold mb-0"><%= @account.user_id %></p>
          </div>
        </div>
        <div class="col-md-6">
          <div class="bg-light p-3 rounded-3">
            <small class="text-muted d-block mb-1">Moneda</small>
            <p class="fw-bold mb-0"><%= @account.currency %></p>
          </div>
        </div>

        <div class="col-md-6">
          <div class="bg-light p-3 rounded-3" >
          <small class="text-muted d-block mb-1">Saldo Disponible</small>
          <p class="text-success fw-bold fs-4 mb-0">
          <span data-controller="currency-symbol" data-currency="<%= @account.currency %>">
            <%= number_to_currency(@account.balance.total_amount,unit: "", delimiter: ",") %>
          </span>
          </p>
          </div>
        </div>
      </div>
      <hr class="my-4 text-muted">

      <div class="d-flex flex-wrap gap-2 justify-content-center">
        <%= link_to accounts_path,
            class: "btn btn-outline-primary d-flex align-items-center",
            data: { bs_toggle: "tooltip" },
            title: "Regresar a Cuentas" do %>
          <i class="fa-solid fa-arrow-left me-2"></i>
        <% end %>
        <%= link_to account_path(@account),
            class: "btn btn-outline-danger d-flex align-items-center",
            data: {
              turbo_method: :delete,
              turbo_confirm: "¿Estás seguro de que deseas eliminar esta cuenta?",
              bs_toggle: "tooltip"
            },
            title: "Eliminar Cuenta" do %>
          <i class="fa-solid fa-trash me-2"></i>
        <% end %>

        <%= link_to edit_account_path(@account),
            class: "btn btn-outline-secondary d-flex align-items-center",
            data: { bs_toggle: "tooltip" },
            title: "Editar Cuenta" do %>
          <i class="fa-solid fa-pen me-2"></i>
        <% end %>

        <%= link_to new_account_my_transaction_path(@account),
            class: "btn btn-outline-success d-flex align-items-center",
            data: { bs_toggle: "tooltip" },
            title: "Agregar Transacción" do %>
          <i class="fa-solid fa-plus me-2"></i>Agregar Transacción
        <% end %>

        <%= link_to "#",
          class: "btn btn-outline-info d-flex align-items-center",
          data: {
          controller: "mytransactions",
          action: "click->mytransactions#displayTransactions",
          bs_toggle: "tooltip"
         },
        title: "Ver Transacciones" do %>
        <i class="fa-solid fa-list me-2"></i>Ver Transacciones
        <% end %>
      </div>
    </div>
  </div>


</div>

<div class="container mt-4">
  <div class="content-with-navbar-spacing mytransactions d-none">
    <div class="card shadow-lg rounded-4 border-0">
      <div class="card-body p-4">
        <div class="d-flex justify-content-between align-items-center mb-4">
          <h2 class="card-title text-success m-0">
            <i class="fa-solid fa-list me-2"></i>Transacciones
          </h2>
        </div>

        <div class="table-responsive">
          <table class="table table-striped">
            <thead>
              <tr>
                <th scope="col">Categoría</th>
                <th scope="col">Monto</th>
                <th scope="col">Fecha</th>
                <th scope="col">Tipo de Transacción</th>
                <th class="text-muted text-center">Acciones</th>
              </tr>
            </thead>
            <tbody>
              <% @transactions.each do |t| %>
                <tr>
                  <td><%= t.category %></td>
                  <td>
                    <span class="<%= t.mytransaction_type == 'Ingreso' ? 'text-success' : 'text-danger' %> fw-bold">
                      <%= number_to_currency(t.amount, unit: "$") %>
                    </span>
                  </td>
                  <td><%= t.date.strftime("%d-%m-%Y") %></td>
                  <td>
                    <span class="badge <%= t.mytransaction_type == 'Ingreso' ? 'bg-success' : 'bg-danger' %> rounded-pill">
                      <%= t.mytransaction_type %>
                    </span>
                  </td>
                  <td class="text-center">
                    <div class="btn-group" role="group">
                      <%= link_to edit_my_transaction_path(account_id: t.account_id, id: t.id),
                          class: "btn btn-sm btn-outline-secondary",
                          data: { bs_toggle: "tooltip" },
                          title: "Editar" do %>
                        <i class="fas fa-pencil-alt"></i>
                      <% end %>
                      <%= link_to my_transaction_path(account_id: t.account_id, id: t.id),
                          class: "btn btn-sm btn-outline-danger",
                          data: {
                            turbo_method: :delete,
                            turbo_confirm: "¿Estás seguro de que deseas eliminar esta transacción?",
                            bs_toggle: "tooltip"
                          },
                          title: "Eliminar" do %>
                        <i class="fas fa-trash"></i>
                      <% end %>
                      <%= link_to my_transaction_path(account_id: t.account_id, id: t.id),
                          class: "btn btn-sm btn-outline-info",
                          data: { bs_toggle: "tooltip" },
                          title: "Ver Detalles" do %>
                        <i class="fas fa-eye"></i>
                      <% end %>
                    </div>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>

        <% if @transactions.empty? %>
          <div class="alert alert-info text-center" role="alert">
            No hay transacciones registradas
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>